version: "3.8"
networks:
  todo-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: pre-todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sa2008
      MYSQL_DATABASE: todo
      MYSQL_PASSWORD: sa2008
    ports:
      - "3300:3306"
    networks:
      - todo-net

  redis:
    image: redis:latest
    container_name: pre-todo-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
    command: [ "redis-server", "--protected-mode", "no" ]
    networks:
      - todo-net

  app:
    build: .
    image: todo-app:latest
    container_name: todo-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pre-todo-mysql:3306/todo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sa2008
      SPRING_REDIS_HOST: pre-todo-redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - todo-net